name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zrok
        run: |
          wget https://github.com/openziti/zrok/releases/download/v0.4.38/zrok_0.4.38_linux_amd64.tar.gz
          tar -xvzf zrok_0.4.38_linux_amd64.tar.gz
          sudo mv zrok /usr/local/bin/

      - name: Access share using zrok
        env:
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        run: |
          echo "${{ secrets.ZROK_TOKEN }}" > ~/zrok.token
          zrok access private $(cat ~/zrok.token)

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 1991 cilin@127.0.0.1 "cd /var/www/html && git pull origin main && sudo systemctl restart nginx"
