   name: Deploy Static Website

    on:
      push:
        branches:
          - [main]

    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Deploy to Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_KEY }}
            script: |
              cd /var/www/html/static-website
              git pull origin production-branch
              sudo systemctl reload apache2
