name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH using zrok
        env:
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        run: |
          chmod 600 ~/.ssh/id_rsa
          echo "$ZROK_TOKEN" > ~/zrok.token
          ssh -o StrictHostKeyChecking=no -p 1991 cilin@127.0.0.1 "cd /var/www/html && git pull origin main && sudo systemctl restart nginx"
