name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH using zrok
        env:
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        run: |
          echo "$ZROK_TOKEN" > ~/zrok.token
          zrok access private $ZROK_TOKEN
          ssh -o StrictHostKeyChecking=no -p 1991 cilin@127.0.0.1 "cd /var/www/html && git pull origin main && sudo systemctl restart nginx"
