name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Client and SSHPass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo -e "Host serveo.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        echo -e "Host foo.serveo.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - name: Test SSH Connection
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -J serveo.net cilin@foo "echo 'SSH connection successful'"
    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      if: success()
      run: |
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -J serveo.net" . cilin@foo:/var/www/html
    - name: Start HTTP Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      if: success()
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -J serveo.net cilin@foo "nohup ssh -R 80:localhost:3000 serveo.net"
    - name: Cleanup
      run: rm -f /tmp/deploy_key
