name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Client and SSHPass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo -e "Host foo.serveo.net\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Test SSH Connection
      env:
        SSH_PASSWORD: sio@1231999
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -J serveo.net cilin@foo.serveo.net "echo 'SSH connection successful'"
