name: Deploy static website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in the repository
      run: ls -R

    - name: Deploy files to Ubuntu server
      uses: appleboy/scp-action@v0.1.2
      with:
        source: "*"
        target: "cilin@51d9-143-44-165-168.ngrok-free.app:/var/www/html"
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Apache
      run: |
        ssh -o StrictHostKeyChecking=no user@51d9-143-44-165-168.ngrok-free.app 'sudo systemctl restart apache2'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
