name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        mkdir -p ~/.ssh
        ssh-keyscan -H foo.serveo.net >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        rsync -avz -q --delete -e "ssh -i /tmp/deploy_key" ./ cilin@foo.serveo.net:/var/www/html

    - name: Cleanup
      run: |
        rm -f /tmp/deploy_key
