name: Deploy to Ubuntu Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 192.168.0.172 >> ~/.ssh/known_hosts

    - name: Run Commands on Remote Server
      run: |
        ssh -o StrictHostKeyChecking=no cilin@192.168.0.172 << 'EOF'
          # Your remote command here
          echo "Hello, this is from GitHub Actions!"
        EOF
